/* =========================================================================
   common.js — shared by every page.

   Contents
     FC.util        tiny DOM helpers
     FC.prefs       remembered choices (edition, theme, citations) — optional,
                    wrapped in try/catch because storage may be unavailable
     FC.EDITIONS, FC.EDITION_RULES   the three editions, and where their boards differ
     FC.img         modern image formats (AVIF, WebP) with JPEG fallback
     FC.sq          what we know about each square (names, verses, images, Barros's segments)
     FC.tokens      the players' markers, drawn as small SVGs
     FC.Viewer      the pan-and-zoom board with clickable squares and tokens
     FC.annotate    builds the full annotation of a square (used by Play and Atlas)
     FC.drawer      a side sheet for reading annotations without leaving the page
     citation pop-ups, theme button, "hide references" toggle, draft notice,
     FC.afterNotice (run something once the draft notice is dismissed)

   Data (window.FC.board, .annotations, .text, .biblio, .story, .about) comes from
   data/*.js, generated by tools/build_data.py from the files in content/.
   ========================================================================= */
window.FC = window.FC || {};
/* The edition's version, as given in the footers of the pages, the About credits, README,
   CHANGELOG.md and CITATION.cff: change them all together. */
FC.VERSION = '0.3';
FC.VERSION_DATE = 'October 2026';

/* ---------------------------------------------------------------- util */
FC.util = {
  $: (sel, root = document) => root.querySelector(sel),
  $$: (sel, root = document) => Array.from(root.querySelectorAll(sel)),
  esc: s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])),
  /** Create an element from an HTML string. */
  html(str) { const t = document.createElement('template'); t.innerHTML = str.trim(); return t.content.firstElementChild; },
  clamp: (v, a, b) => Math.max(a, Math.min(b, v)),
  plural: (n, one, many) => `${n} ${Math.abs(n) === 1 ? one : many}`,
  reducedMotion: () => matchMedia('(prefers-reduced-motion: reduce)').matches,
};

/* ---------------------------------------------------------------- prefs */
FC.prefs = {
  // Every key is prefixed, because all the project sites of one GitHub account share one
  // storage origin (user.github.io). js/theme.js and 404.html read 'theme' with the same prefix.
  PREFIX: 'filosofia-cortesana:',
  get(k, d) { try { const v = localStorage.getItem(this.PREFIX + k); return v === null ? d : JSON.parse(v); } catch (e) { return d; } },
  set(k, v) { try { localStorage.setItem(this.PREFIX + k, JSON.stringify(v)); } catch (e) { /* storage unavailable: fine */ } },
  /** Remove keys altogether (not merely set them to null). */
  forget(...keys) { keys.forEach(k => { try { localStorage.removeItem(this.PREFIX + k); } catch (e) { /* fine */ } }); },
};

/* ---------------------------------------------------------------- editions */
FC.EDITIONS = {
  C: { id: 'C', short: 'Naples 1588 (with this board)', printer: 'Joseph Cacchij', long: 'Naples, Joseph Cacchij, 1588 — with Mario Cartaro’s bilingual board (the sheet you see)' },
  M: { id: 'M', short: 'Madrid 1587, 2nd ed.', printer: 'Pedro Madrigal', long: 'Madrid, Pedro Madrigal, 1587 — second edition, with the full “Declaración del juego” (board lost)' },
  G: { id: 'G', short: 'Madrid 1587, 1st ed.', printer: 'widow of Alonso Gómez', long: 'Madrid, widow of Alonso Gómez, 1587 — first edition (board lost; Poverty on 59; other Labor verses)' },
};
/* Where the editions' boards differ from Cartaro's, in one place. The princeps (G) puts
   Poverty on 59, so 60 is plain; it printed eight Labor couplets of its own, in this order
   (Lucero 2016, collation tables). Its board is lost: we lay them on Cartaro's Labor squares
   in order. (The rules engine, js/game.js, has its own copy of the Poverty square.) */
FC.EDITION_RULES = {
  C: { poverty: 60, plain: [], labour: null, boardMarks: [] },
  M: { poverty: 60, plain: [], labour: null, boardMarks: [] },
  G: { poverty: 59, plain: [60], labour: { 12: 'g1', 17: 'g2', 23: 'g3', 30: 't5', 34: 't7', 41: 'g6', 48: 't4', 57: 't3' },
       boardMarks: [{ n: 59, text: 'Poverty (1587)' }, { n: 60, text: 'plain (1587)' }] },
};
FC.rules = ed => FC.EDITION_RULES[ed] || FC.EDITION_RULES.C;

/* ---------------------------------------------------------------- images */
/* Every derived JPEG under img/ has .avif and .webp twins (tools/make_images.py).
   In markup use FC.img.pic(); where a script sets src, wait for FC.img.best. */
FC.img = (function () {
  const AVIF = 'data:image/avif;base64,AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAADrbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAAAAAOcGl0bQAAAAAAAQAAAB5pbG9jAAAAAEQAAAEAAQAAAAEAAAETAAAAIQAAAChpaW5mAAAAAAABAAAAGmluZmUCAAAAAAEAAGF2MDFDb2xvcgAAAABqaXBycAAAAEtpcGNvAAAAFGlzcGUAAAAAAAAAAQAAAAEAAAAQcGl4aQAAAAADCAgIAAAADGF2MUOBAAwAAAAAE2NvbHJuY2x4AAEADQAGgAAAABdpcG1hAAAAAAAAAAEAAQQBAoMEAAAAKW1kYXQSAAoIGAAGiAhoNCAyExlHh4Yhh5555oAAAJBAyRxgimo=';
  const WEBP = 'data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAAAAAAfQ//73v/+BiOh/AAA=';
  const probe = src => new Promise(r => { const i = new Image(); i.onload = () => r(i.width > 0); i.onerror = () => r(false); i.src = src; });
  const best = probe(AVIF).then(a => a ? 'avif' : probe(WEBP).then(w => w ? 'webp' : 'jpg'));
  const swap = (src, ext) => ext === 'jpg' ? src : src.replace(/\.jpg$/, '.' + ext);
  /** <picture> for a .jpg that has twins. attrs: extra attributes for the <img>;
      srcset: [[url, width], …] for a size ladder, with sizes. */
  function pic(src, alt, attrs = '', ladder = null, sizes = '') {
    const set = ext => ladder ? ladder.map(([u, w]) => `${swap(u, ext)} ${w}w`).join(', ') : swap(src, ext);
    const sz = ladder && sizes ? ` sizes="${sizes}"` : '';
    return `<picture><source type="image/avif" srcset="${set('avif')}"${sz}><source type="image/webp" srcset="${set('webp')}"${sz}>` +
      `<img src="${src}"${ladder ? ` srcset="${set('jpg')}"${sz}` : ''} alt="${FC.util.esc(alt)}" ${attrs}></picture>`;
  }
  return { best, swap, pic };
})();

/* ---------------------------------------------------------------- squares */
FC.sq = (function () {
  const B = () => FC.board;
  const LABOUR = [4, 12, 17, 23, 30, 34, 41, 48, 57];
  // Which fixed verse translation (TRANSLATION_GUIDE.md id) belongs to which square.
  const VID = { 1: 's1', 4: 't0', 12: 't1', 17: 't2', 23: 't3', 30: 't4', 34: 't5', 41: 't6', 48: 't7', 57: 't8',
    7: 'h7', 10: 'h10', 15: 'h15', 20: 'h20', 26: 'h26', 28: 'h28', 32: 'h32', 36: 'h36', 39: 'h39',
    43: 'h43', 46: 'h46', 51: 'h51', 53: 'h53', 55: 'h55', 60: 'h60', 63: 'h63' };
  const G_LABOUR = FC.EDITION_RULES.G.labour;

  function annId(n, ed) {
    const r = FC.rules(ed);
    if (n === r.poverty && r.poverty !== 60) return 'sq60';
    if (r.plain.includes(n)) return 'plain';
    return FC.annotations['sq' + n] ? 'sq' + n : 'plain';
  }
  function data(n) { return B().squares[n - 1]; }
  function adorned(n, ed) {
    if (n === FC.rules(ed).poverty) return true;
    if (FC.rules(ed).plain.includes(n)) return false;
    return !!FC.annotations['sq' + n];
  }
  function name(n, ed) {
    const a = FC.annotations[annId(n, ed)];
    if (!a || a.id === 'plain') return `Square ${n}`;
    return a.title_en.replace(/\s*\(.*\)$/, '');
  }
  /** The verse on square n in edition ed:
      {vid, en, lit, es_book, book (whose Spanish es_book is: 'C', 'G' or 'C-not-G'),
       es_board, it_board, gloss_it, princeps_only, es_m (Madrigal's own wording, if recorded)} */
  function verse(n, ed) {
    const d = data(n), V = B().verses, r = FC.rules(ed);
    let vid = VID[n];
    if (r.labour && r.labour[n]) vid = r.labour[n];
    if (n === r.poverty) vid = 'h60';
    if (r.plain.includes(n)) vid = null;
    const v = vid ? V[vid] : null;
    if (!v) return null;
    const moved = ed === 'G' && (G_LABOUR[n] || n === r.poverty || r.plain.includes(n));
    const gEs = ed === 'G' && G_LABOUR[n] && B().G_labour_es && B().G_labour_es[n];
    const mSeg = ed === 'M' && FC.text ? FC.text.M.find(s => s.kind === 'verse' && s.squares.includes(String(n))) : null;
    return {
      vid, en: v.en, lit: v.lit,
      es_book: gEs || v.es.replace(/\s*\((?:1587 )?princeps only\)/, ''),
      book: gEs ? 'G' : ed === 'G' ? 'C-not-G' : 'C',
      es_m: mSeg ? mSeg.es : '',
      es_board: moved ? '' : d.es, it_board: moved ? '' : d.it, gloss_it: moved ? '' : d.it_gloss,
      princeps_only: vid.startsWith('g'),
    };
  }
  const pad = n => String(n).padStart(2, '0');
  const tile = n => `img/sq/tile-${pad(n)}.jpg`;
  const detail = n => `img/sq/detail-${pad(n)}.jpg`;
  /** Barros's own prose about square n (Naples 1588 segments; Madrigal additions too). */
  function barros(n) {
    const tag = LABOUR.includes(n) ? ['labour', String(n)] : [String(n)];
    const C = FC.text.C.filter(s => s.kind !== 'rules' && s.squares.some(x => tag.includes(x)));
    const M = FC.text.M.filter(s => s.kind !== 'rules' && s.squares.includes(String(n)));
    return { C, M };
  }
  return { LABOUR, VID, G_LABOUR, data, name, verse, tile, detail, barros, adorned, annId };
})();

/* ---------------------------------------------------------------- tokens */
/* Barros's worked example uses a ring, a real de a dos and a doblón as markers,
   and asks that every player have "su señal diferente". */
FC.tokens = {
  list: [
    { id: 'ring', name: 'a ring (sortija)', color: '#b08a2e' },
    { id: 'real', name: 'a real de a dos', color: '#8f969c' },
    { id: 'doblon', name: 'a doblón', color: '#c9a13b' },
    { id: 'seal', name: 'a wax seal', color: '#9c2f22' },
    { id: 'key', name: 'a key', color: '#5b5147' },
    { id: 'rosary', name: 'a rosary bead', color: '#2f5d62' },
  ],
  /** SVG markup for a marker, centered on 0,0 in a 40×40 box. */
  glyph(id) {
    switch (id) {
      case 'ring': return '<circle r="12" fill="none" stroke="#b08a2e" stroke-width="5"/><circle cy="-13" r="5" fill="#9c2f22" stroke="#6d1f16" stroke-width="1.5"/>';
      case 'real': return '<circle r="15" fill="#c7ccd0" stroke="#6f767c" stroke-width="2"/><path d="M0-9v18M-9 0h18" stroke="#5f666b" stroke-width="2.5"/><circle r="11" fill="none" stroke="#8f969c" stroke-width="1" stroke-dasharray="2 2"/>';
      case 'doblon': return '<circle r="15" fill="#e2bd57" stroke="#8a6a1b" stroke-width="2"/><rect x="-6" y="-8" width="12" height="15" rx="2" fill="none" stroke="#8a6a1b" stroke-width="2"/><path d="M-6-2h12" stroke="#8a6a1b" stroke-width="1.5"/>';
      case 'seal': return '<path d="M0-15l4 3 5-1 1 5 4 3-2 5 2 5-4 3-1 5-5-1-4 3-4-3-5 1-1-5-4-3 2-5-2-5 4-3 1-5 5 1z" fill="#a73325" stroke="#6d1f16" stroke-width="1.5"/><circle r="6" fill="none" stroke="#e8b2a6" stroke-width="1.5"/>';
      case 'key': return '<circle cx="-7" r="7" fill="none" stroke="#4b433c" stroke-width="4"/><path d="M0 0h15M10 0v6M14 0v5" stroke="#4b433c" stroke-width="4" stroke-linecap="round"/>';
      case 'rosary': return '<circle r="13" fill="#2f5d62" stroke="#1b3a3e" stroke-width="2"/><path d="M0-8v16M-5-3h10" stroke="#d9e8e6" stroke-width="2.5"/>';
    }
    return '<circle r="12" fill="#777"/>';
  },
  /** A small marker icon, on the same light disc as the board tokens, so it shows on dark grounds. */
  svg(id, cls = 'tok-ic') { return `<svg class="${cls}" viewBox="-20 -20 40 40" aria-hidden="true"><circle r="19.5" fill="#faf5ea"/>${this.glyph(id)}</svg>`; },
};

/* ---------------------------------------------------------------- viewer */
/**
 * FC.Viewer — shows the board sheet with pan & zoom (wheel, drag, pinch, buttons, keys),
 * an SVG overlay of the 63 squares (clickable, and reachable by keyboard when the viewer
 * has tools and an onSquare handler), and players' tokens.
 * Coordinates everywhere are fractions of the sheet (0..1).
 * The image climbs a ladder of sizes, fetching only the smallest one sharp enough for
 * the current zoom (each in the best format the browser decodes).
 */
const BOARD_LADDER = [['img/board/board-800.jpg', 800], ['img/board/board-1200.jpg', 1200],
  ['img/board/board-2000.jpg', 2000], ['img/board/board-full.jpg', 2594]];
FC.BOARD_ALT = 'Mario Cartaro’s engraved board, Naples 1588: a track of 63 numbered squares divided by balusters. ' +
  'A gate at bottom left leads to square 1; the numbers run counter-clockwise round the outer ring and then inward in a ' +
  'second ring to the palm at square 63, in the center. Emblematic figures fill the four corners. British Museum 1869,0410.2463.+';
FC.Viewer = class {
  constructor(container, opts = {}) {
    this.el = container;
    // wheel: zoom with the mouse wheel (false in the introduction, where the wheel scrolls the page)
    this.opts = Object.assign({ src: null, hotspots: true, tools: true, onSquare: null, tips: true, wheel: true }, opts);
    const S = FC.board.sheet;
    this.aspect = S.h / S.w;
    this.ladder = !this.opts.src || /board\/board-/.test(this.opts.src) ? BOARD_LADDER : null;
    this.level = -1;
    this.keyed = !!(this.opts.tools && this.opts.onSquare && this.opts.hotspots);
    this.el.classList.add('viewer');
    this.el.innerHTML = `
      <div class="stage">
        <img alt="${FC.util.esc(FC.BOARD_ALT)}"${this.ladder ? '' : ` src="${this.opts.src}"`}>
        <svg class="overlay" viewBox="0 0 1000 ${Math.round(1000 * this.aspect)}" preserveAspectRatio="none"${this.keyed ? '' : ' aria-hidden="true"'}><g class="hots"></g><g class="names" hidden aria-hidden="true"></g><g class="marks" aria-hidden="true"></g><g class="toks" aria-hidden="true"></g></svg>
      </div>
      ${this.opts.tools ? `<div class="viewer-tools"><button type="button" data-z="in" aria-label="Zoom in">+</button><button type="button" data-z="out" aria-label="Zoom out">−</button><button type="button" data-z="fit" aria-label="Show the whole board">⤢</button>
        <div class="pan-pad"><button type="button" data-pan="0,1" aria-label="Move the view up">↑</button><button type="button" data-pan="1,0" aria-label="Move the view left">←</button><button type="button" data-pan="-1,0" aria-label="Move the view right">→</button><button type="button" data-pan="0,-1" aria-label="Move the view down">↓</button></div></div>` : ''}
      <div class="label-tip" hidden></div>`;
    this.stage = this.el.querySelector('.stage');
    this.svg = this.el.querySelector('svg');
    this.tip = this.el.querySelector('.label-tip');
    this.s = 1; this.x = 0; this.y = 0;
    if (this.opts.hotspots) this.drawHotspots();
    this.bind();
    if (typeof ResizeObserver === 'function') { this.ro = new ResizeObserver(() => this.layout()); this.ro.observe(this.el); }
    else { this.ro = null; this._onResize = () => this.layout(); addEventListener('resize', this._onResize); }   // older browsers
    this.layout();
  }
  /** Stop observing the container (call before replacing a viewer with another). */
  destroy() { if (this.ro) this.ro.disconnect(); else removeEventListener('resize', this._onResize); }
  /** fraction → overlay units */
  u(p) { return [p[0] * 1000, p[1] * 1000 * this.aspect]; }
  drawHotspots() {
    const g = this.svg.querySelector('.hots');
    g.innerHTML = FC.board.squares.map(s => {
      const pts = s.quad.map(p => this.u(p).join(',')).join(' ');
      const kb = this.keyed ? ` role="button" tabindex="-1" aria-label="Square ${s.n}"` : '';
      return `<polygon class="hot" data-n="${s.n}" points="${pts}"${kb}><title>${s.n}</title></polygon>`;
    }).join('');
  }
  /** Move keyboard focus to square n on the board, bringing it into view. */
  focusHot(n) {
    n = FC.util.clamp(n, 1, 63);
    const p = this.svg.querySelector(`.hot[data-n="${n}"]`);
    if (!p) return;
    this.svg.querySelectorAll('.hot[tabindex="0"]').forEach(x => x.setAttribute('tabindex', '-1'));
    p.setAttribute('tabindex', '0');
    const ed = this.edition || 'C';
    p.setAttribute('aria-label', `Square ${n}${FC.sq.adorned(n, ed) ? ', ' + FC.sq.name(n, ed) : ''}`);
    this.lastHot = n;
    // keep the square on screen
    const c = FC.board.squares[n - 1].center, r = this.el.getBoundingClientRect();
    const px = this.x + c[0] * this.base * this.s, py = this.y + c[1] * this.base * this.aspect * this.s;
    if (px < 40 || py < 40 || px > r.width - 40 || py > r.height - 40) {
      this.x = r.width / 2 - c[0] * this.base * this.s; this.y = r.height / 2 - c[1] * this.base * this.aspect * this.s; this.apply(true);
    }
    p.focus({ preventScroll: true });
  }
  bind() {
    const el = this.el;
    let drag = null, pinch = null, moved = false;
    const pts = new Map();
    el.addEventListener('pointerdown', e => {
      el.setPointerCapture(e.pointerId);
      pts.set(e.pointerId, [e.clientX, e.clientY]);
      moved = false;
      if (pts.size === 1) drag = { x: e.clientX, y: e.clientY, ox: this.x, oy: this.y, t: e.target };
      if (pts.size === 2) { const [a, b] = [...pts.values()]; pinch = { d: Math.hypot(a[0] - b[0], a[1] - b[1]), s: this.s, cx: (a[0] + b[0]) / 2, cy: (a[1] + b[1]) / 2 }; drag = null; }
    });
    el.addEventListener('pointermove', e => {
      if (!pts.has(e.pointerId)) { this.hover(e); return; }
      pts.set(e.pointerId, [e.clientX, e.clientY]);
      if (pinch && pts.size === 2) {
        const [a, b] = [...pts.values()]; const d = Math.hypot(a[0] - b[0], a[1] - b[1]);
        this.zoomAt(pinch.s * d / pinch.d / this.s, pinch.cx, pinch.cy); moved = true; return;
      }
      if (drag) {
        const dx = e.clientX - drag.x, dy = e.clientY - drag.y;
        if (Math.abs(dx) + Math.abs(dy) > 4) moved = true;
        this.x = drag.ox + dx; this.y = drag.oy + dy; this.apply();
      }
    });
    const end = e => {
      pts.delete(e.pointerId);
      if (pts.size < 2) pinch = null;
      if (drag && !moved) this.click(drag.t, e);
      if (!pts.size) drag = null;
    };
    el.addEventListener('pointerup', end);
    el.addEventListener('pointercancel', e => { pts.delete(e.pointerId); drag = null; pinch = null; });
    el.addEventListener('pointerleave', () => { this.tip.hidden = true; });
    el.addEventListener('wheel', e => {
      if (!this.opts.wheel && !e.ctrlKey) return;                  // let the page scroll
      e.preventDefault(); this.zoomAt(Math.exp(-e.deltaY * 0.0016), e.clientX, e.clientY);
    }, { passive: false });
    el.querySelectorAll('[data-z], [data-pan]').forEach(b => b.addEventListener('pointerdown', e => e.stopPropagation()));
    el.querySelectorAll('[data-z]').forEach(b => b.addEventListener('click', e => {
      e.stopPropagation();
      const r = el.getBoundingClientRect();
      if (b.dataset.z === 'fit') this.fit(true);
      else this.zoomAt(b.dataset.z === 'in' ? 1.5 : 1 / 1.5, r.left + r.width / 2, r.top + r.height / 2, true);
    }));
    el.querySelectorAll('[data-pan]').forEach(b => b.addEventListener('click', e => {
      e.stopPropagation(); this.pan(...b.dataset.pan.split(',').map(Number));
    }));
    el.addEventListener('keydown', e => {
      const r = el.getBoundingClientRect();
      const hot = e.target.closest && e.target.closest('.hot');
      if (hot && this.keyed) {                                     // moving from square to square
        const n = +hot.dataset.n;
        const step = { ArrowRight: 1, ArrowUp: 1, ArrowLeft: -1, ArrowDown: -1, Home: -99, End: 99 }[e.key];
        if (step) { e.preventDefault(); this.focusHot(n + step); return; }
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); this.opts.onSquare(n); return; }
        if (e.key === 'Escape') { e.preventDefault(); e.stopPropagation(); el.focus(); return; }
      }
      if (e.target !== el) return;                                 // the buttons handle themselves
      if (e.key === '+' || e.key === '=') this.zoomAt(1.3, r.left + r.width / 2, r.top + r.height / 2, true);
      else if (e.key === '-' || e.key === '−') this.zoomAt(1 / 1.3, r.left + r.width / 2, r.top + r.height / 2, true);
      else if (e.key === '0') this.fit(true);
      else if (e.key === 'Enter' && this.keyed) this.focusHot(this.lastHot || 1);
      else {
        const P = { ArrowLeft: [1, 0], ArrowRight: [-1, 0], ArrowUp: [0, 1], ArrowDown: [0, -1] }[e.key];
        if (!P) return;
        this.pan(...P);
      }
      e.preventDefault();
    });
    if (this.opts.tools) {
      el.tabIndex = 0;
      el.setAttribute('role', 'group');
      el.setAttribute('aria-roledescription', 'board viewer');
      el.setAttribute('aria-label', 'The board. Arrow keys move the view, + and − zoom, 0 shows the whole board' +
        (this.keyed ? '; Enter goes to the squares, where the arrow keys step from square to square and Enter opens one.' : '.'));
    }
  }
  /** Move the view by a fifth of its width (dx) or height (dy). */
  pan(dx, dy) { this.x += dx * this.W * 0.2; this.y += dy * this.H * 0.2; this.apply(true); }
  hover(e) {
    if (!this.opts.tips) return;
    const t = e.target.closest && e.target.closest('.hot');
    if (!t) { this.tip.hidden = true; return; }
    const n = +t.dataset.n, ed = this.edition || 'C';
    const r = this.el.getBoundingClientRect();
    this.tip.textContent = `${n} · ${FC.sq.name(n, ed)}`;
    this.tip.hidden = false;
    this.tip.style.left = Math.min(e.clientX - r.left + 14, r.width - 180) + 'px';
    this.tip.style.top = (e.clientY - r.top + 14) + 'px';
  }
  click(target) {
    const t = target.closest && target.closest('.hot');
    if (t && this.opts.onSquare) this.opts.onSquare(+t.dataset.n);
  }
  layout() {
    const r = this.el.getBoundingClientRect();
    this.W = r.width; this.H = r.height;
    const baseW = Math.min(r.width, r.height / this.aspect);
    this.base = baseW;
    this.stage.style.width = baseW + 'px';
    this.stage.style.height = baseW * this.aspect + 'px';
    if (!this._fitted) { this.fit(false); this._fitted = true; } else this.apply();
  }
  fit(anim) {
    this.s = 1;
    this.x = (this.W - this.base) / 2; this.y = (this.H - this.base * this.aspect) / 2;
    this.apply(anim);
  }
  zoomAt(f, cx, cy, anim) {
    const r = this.el.getBoundingClientRect();
    const ns = FC.util.clamp(this.s * f, 0.6, 9);
    f = ns / this.s;
    const px = cx - r.left, py = cy - r.top;
    this.x = px - (px - this.x) * f; this.y = py - (py - this.y) * f; this.s = ns;
    this.apply(anim);
  }
  /** Zoom so that the rectangle (fractions of the sheet) fills the view. */
  focusRect(x0, y0, x1, y1, anim = true, pad = 0.08) {
    const w = (x1 - x0) * this.base, h = (y1 - y0) * this.base * this.aspect;
    const s = FC.util.clamp(Math.min(this.W / (w * (1 + pad * 2)), this.H / (h * (1 + pad * 2))), 0.6, 9);
    this.s = s;
    this.x = this.W / 2 - ((x0 + x1) / 2) * this.base * s;
    this.y = this.H / 2 - ((y0 + y1) / 2) * this.base * this.aspect * s;
    this.apply(anim);
  }
  focusSquare(n, anim = true, zoom = 3.2) {
    const q = FC.board.squares[n - 1].quad;
    const xs = q.map(p => p[0]), ys = q.map(p => p[1]);
    const cx = (Math.min(...xs) + Math.max(...xs)) / 2, cy = (Math.min(...ys) + Math.max(...ys)) / 2;
    const half = 0.5 / zoom;
    this.focusRect(cx - half, cy - half * 0.8, cx + half, cy + half * 0.8, anim, 0);
  }
  /** Fetch the smallest board image sharp enough for the current zoom, if not already shown. */
  sharpen() {
    if (!this.ladder || !this.base) return;
    const need = this.base * this.s * Math.min(window.devicePixelRatio || 1, 2);
    let k = this.ladder.findIndex(([, w]) => w >= need * 0.9);
    if (k < 0) k = this.ladder.length - 1;
    if (k <= this.level) return;
    this.level = k;
    FC.img.best.then(ext => {
      if (this.level !== k) return;                       // a larger one was asked for meanwhile
      const url = FC.img.swap(this.ladder[k][0], ext), img = this.stage.querySelector('img');
      if (!img.getAttribute('src')) { img.src = url; return; }
      const hi = new Image();
      hi.onload = () => { if (this.level === k) img.src = url; };
      hi.src = url;
    });
  }
  apply(anim) {
    // keep the sheet in view: center it when smaller than the viewer, otherwise stop at its edges
    const w = this.base * this.s, h = this.base * this.aspect * this.s;
    this.x = w <= this.W ? (this.W - w) / 2 : FC.util.clamp(this.x, this.W - w, 0);
    this.y = h <= this.H ? (this.H - h) / 2 : FC.util.clamp(this.y, this.H - h, 0);
    this.sharpen();
    this.stage.style.transition = anim ? 'transform .7s cubic-bezier(.3,.1,.2,1)' : 'none';
    this.stage.style.transform = `translate(${this.x}px, ${this.y}px) scale(${this.s})`;
  }
  /** Mark squares with a CSS class ('focus' or 'variant'). */
  mark(ns, cls) {
    this.svg.querySelectorAll('.hot.' + cls).forEach(p => p.classList.remove(cls));
    [].concat(ns || []).forEach(n => { const p = this.svg.querySelector(`.hot[data-n="${n}"]`); if (p) p.classList.add(cls); });
  }
  /** Show where edition ed's board differs from Cartaro's (the princeps' Poverty on 59). */
  showEdition(ed) {
    const r = FC.rules(ed);
    this.edition = ed;
    this.mark(r.poverty !== 60 ? [r.poverty] : [], 'variant');
    this.labels(r.boardMarks);
  }
  /** English names written over the adorned squares (a reading aid; off by default). */
  names(on, ed = 'C') {
    const g = this.svg.querySelector('.names');
    g.hidden = !on;
    if (!on) return;
    let h = '';
    for (let n = 1; n <= 63; n++) {
      if (!FC.sq.adorned(n, ed)) continue;
      const nm = FC.sq.name(n, ed).replace(/^The /, ''), c = this.u(FC.board.squares[n - 1].center);
      const w = nm.length * 6.4 + 10;
      h += `<g transform="translate(${c[0].toFixed(1)},${(c[1] + 18).toFixed(1)})"><rect x="${-w / 2}" y="-9" width="${w}" height="16" rx="3" class="name-bg"/><text class="name-tx" text-anchor="middle" y="3">${FC.util.esc(nm)}</text></g>`;
    }
    g.innerHTML = h;
  }
  /** Small labels written on the overlay (used for the princeps' Poverty on 59). */
  labels(list) {
    const g = this.svg.querySelector('.marks');
    g.innerHTML = (list || []).map(l => {
      const c = this.u(FC.board.squares[l.n - 1].center);
      return `<text class="variant-label" x="${c[0]}" y="${c[1] + 26}" text-anchor="middle">${FC.util.esc(l.text)}</text>`;
    }).join('');
  }
  /**
   * Draw tokens. players: [{id, token, color, pos}] ; pos 0 = before the gate.
   * Several tokens on the same place are fanned out.
   */
  tokens(players) {
    const g = this.svg.querySelector('.toks');
    const byPos = {};
    players.forEach(p => { (byPos[p.pos] = byPos[p.pos] || []).push(p); });
    const gate = this.u([0.13, 0.85]);
    let out = '';
    Object.entries(byPos).forEach(([pos, ps]) => {
      pos = +pos;
      const c = pos === 0 ? gate : this.u(FC.board.squares[pos - 1].center);
      ps.forEach((p, i) => {
        const k = ps.length, ang = (i / k) * Math.PI * 2, rad = k > 1 ? 20 : 0;
        const x = c[0] + Math.cos(ang) * rad, y = c[1] + Math.sin(ang) * rad;
        out += `<g class="token" data-player="${p.id}" transform="translate(${x.toFixed(1)},${y.toFixed(1)})">
          <circle r="21" fill="rgba(250,245,234,.92)" stroke="${p.color}" stroke-width="4"/>
          <g transform="scale(0.85)">${FC.tokens.glyph(p.token)}</g></g>`;
      });
    });
    g.innerHTML = out;
  }
};

/* ---------------------------------------------------------------- annotate */
/**
 * FC.annotate(n, edition) → HTML for square n (1..63), or for a feature id
 * ('gate', 'centre-sea', 'corner-clock', 'title', …).
 */
FC.annotate = function (key, ed = 'C', opts = {}) {
  const { esc } = FC.util;
  const isSq = typeof key === 'number';
  const aid = isSq ? FC.sq.annId(key, ed) : key;
  const a = FC.annotations[aid] || FC.annotations.plain;
  const n = isSq ? key : null;
  const title = isSq ? FC.sq.name(n, ed) : a.title_en;
  const d = isSq ? FC.sq.data(n) : null;
  const r = FC.rules(ed);
  let h = '';
  h += `<div class="sq-head">${n ? `<div class="sq-num">${n}</div>` : ''}<div><h2 class="sq-title">${esc(title)}</h2>`;
  const subs = [];
  if (a.title_es && a.id !== 'plain') subs.push(`<span lang="es">${esc(a.title_es)}</span>`);
  if (a.board_it && !/^\(none/.test(a.board_it) && a.id !== 'plain') subs.push(`<span lang="it">${esc(a.board_it)}</span>`);
  h += `<div class="sq-sub">${subs.join(' · ')}</div></div></div>`;

  // image
  const img = n ? FC.sq.detail(n) : FC.featureImage(aid);
  if (img) h += `<figure class="sq-figure">${FC.img.pic(img, `${title}: detail of the board`, 'loading="lazy"')}<figcaption>Detail of Cartaro’s board (Naples 1588). © The Trustees of the British Museum.${n ? ` <a href="#" data-show-on-board="${n}">Show on the whole board</a>` : ''}</figcaption></figure>`;

  // edition note for the princeps' Poverty
  if (n && n === r.poverty && r.poverty !== 60) h += `<p class="notice">In the first edition (Madrid, widow of Alonso Gómez, 1587) Poverty stands on square <b>${r.poverty}</b>, not 60; the board printed with that edition is lost. We show Cartaro’s picture of square 60 here.</p>`;
  if (n && r.plain.includes(n)) h += `<p class="notice">In the first edition Poverty stands on ${r.poverty}, so under that edition’s rules this square is plain. On the surviving board (and in the later editions) it is Poverty.</p>`;

  // verse
  const v = n ? FC.sq.verse(n, ed) : null;
  if (v) {
    const lines = t => esc(t).replace(' / ', '<br>');
    h += `<div class="verse"><div class="en">${lines(v.en)}</div><div class="lit">Literally: ${esc(v.lit)}</div><div class="orig">`;
    if (v.es_board) h += `<div><b>Spanish, on the board</b><span lang="es">${lines(v.es_board)}</span></div>`;
    if (v.it_board) h += `<div><b>Italian, on the board</b><span lang="it">${lines(v.it_board)}</span>${v.gloss_it ? `<div class="small muted">(${esc(v.gloss_it)})</div>` : ''}</div>`;
    if (!v.es_board && ed === 'G' && FC.sq.G_LABOUR[n]) h += `<div class="small muted">Cartaro’s board, made for the later text, has a different couplet here: <i lang="es">${esc(FC.sq.data(n).es)}</i>.</div>`;
    // whose Spanish this is (CIT-03): Lucero's quotation of G, or the Naples book
    const bookLab = v.book === 'G'
      ? `Madrid 1587, first edition, as quoted by Lucero Sánchez <span class="cites">(<a class="cite" href="about.html#bib-sanchezEdicionesAntiguasFilosofia2016oct16" data-key="sanchezEdicionesAntiguasFilosofia2016oct16" aria-expanded="false">Lucero Sánchez 2016, 187–88</a>)</span>`
      : v.book === 'C-not-G' ? 'Naples 1588 book (the first edition’s wording is not known to us)' : 'Naples 1588 book';
    h += `<div><b>Spanish, ${bookLab}${v.princeps_only ? '; this couplet only in the first edition' : ''}</b><span lang="es">${lines(v.es_book)}</span></div>`;
    if (v.es_m) h += `<div><b>Spanish, Madrid 1587 (Madrigal), in Ciompi and Seville’s modernized transcription</b><span lang="es">${lines(v.es_m)}</span></div>`;
    h += `</div></div>`;
  }
  // rule
  if (a.rule_short || (d && d.rule)) {
    h += `<div class="rulebox"><div class="ic" aria-hidden="true">☞</div><div>${a.rule_short || ''}`;
    if (d && d.rule) h += `<div class="lab">On the board: <i lang="it">${esc(d.rule)}</i>${d.rule_en ? ` — ${esc(d.rule_en)}` : ''}</div>`;
    h += `</div></div>`;
  }
  const sect = (t, body, open) => body ? `<details class="sect"${open ? ' open' : ''}><summary>${t}</summary>${body}</details>` : '';
  h += sect('What you see', a.see, true);
  h += sect('Why it is here', a.why, true);
  if (n) {
    const b = FC.sq.barros(n);
    if (b.C.length) {
      let bh = `<p class="small muted">Barros’s own explanation, from the Naples 1588 book (Spanish as printed; English translation by this edition). <a href="text.html#${esc(b.C[0].id)}">Read it in the whole book →</a></p>`;
      b.C.forEach(s => {
        bh += `<div class="barros-seg"><div class="meta">${s.page ? 'p. ' + esc(s.page) : 'leaf ' + esc(s.sig)} · Naples 1588</div><div class="es" lang="es">${esc(s.es).replace(/ \/ /g, '<br>')}</div><div class="en">${s.kind === 'verse' ? esc(s.en).replace(' / ', '<br>') : s.en}</div></div>`;
      });
      if (b.M.length && ed === 'M') {   // Madrigal's additions are not in G or C
        bh += `<p class="small muted">Additions and differences in the Madrid (Madrigal) edition of 1587, from Ciompi and Seville’s modernized transcription:</p>`;
        b.M.forEach(s => { bh += `<div class="barros-seg"><div class="meta">fol. ${esc(s.fol)} · Madrid 1587 (Madrigal)</div><div class="es" lang="es">${esc(s.es)}</div><div class="en">${s.en}</div></div>`; });
      }
      h += sect('What Barros says', bh, false);
    }
  }
  h += sect('Historical context', a.context, false);
  h += sect('Differences between the editions', a.variants, false);
  h += sect('What scholars say', a.readings, false);
  if (n && FC.sq.LABOUR.includes(n) && FC.annotations.labour) {
    const L = FC.annotations.labour;
    h += sect('About all nine Labor squares', L.why + L.context + L.variants + L.readings, false);
  }
  if (n && d && d.desc && aid === 'plain') h += `<p class="small muted">On the board: ${esc(d.desc)}</p>`;
  return h;
};
/* The figures around the track: the crop shown in the drawer, and its small version for grids. */
FC.FEATURES = {
  gate: 'entrance_gate', labour: null, 'corner-swan': 'corner_bl_swan', 'corner-dolphin': 'corner_tl_figure',
  'corner-occasion': 'corner_tr_figure', 'corner-clock': 'corner_br_clock', 'centre-sea': 'field', 'centre-man': 'palm_man',
  title: 'signature', plain: null,
};
FC.featureImage = function (aid) {
  const f = FC.FEATURES[aid];
  return f ? `img/feat/${f}.jpg` : (aid === 'labour' ? FC.sq.detail(4) : null);
};
FC.featureThumb = function (aid) {
  if (aid === 'labour') return FC.sq.tile(4);
  if (aid === 'plain') return FC.sq.tile(2);
  if (aid === 'title') return 'img/feat/thumb-title_left.jpg';      // the signature alone is too small to read
  const f = FC.FEATURES[aid];
  return f ? `img/feat/thumb-${f}.jpg` : null;
};

/* ---------------------------------------------------------------- drawer */
FC.drawer = (function () {
  let back, dr, body, titleEl, onClose = null, openedAt = 0, opener = null;
  // everything behind the drawer becomes inert while it is open, except a <dialog>
  // (the draft notice), which must stay usable
  const behind = () => Array.from(document.body.children).filter(el => el !== dr && el !== back && el.tagName !== 'DIALOG');
  function ensure() {
    if (dr) return;
    back = FC.util.html('<div class="drawer-backdrop"></div>');
    dr = FC.util.html(`<div class="drawer" role="dialog" aria-modal="true" aria-label="Annotation">
      <div class="drawer-head"><span class="grow sc drawer-title"></span><button class="btn small" type="button" data-toggle-cites>Hide references in the text</button><button class="btn small" type="button" data-close>Close ✕</button></div>
      <div class="drawer-body"></div></div>`);
    document.body.append(back, dr);
    body = dr.querySelector('.drawer-body'); titleEl = dr.querySelector('.drawer-title');
    dr.inert = true;
    FC.syncCiteToggles();
    // a touch that opened the drawer also sends a click to the backdrop beneath it: ignore that one
    back.addEventListener('click', () => { if (performance.now() - openedAt > 400) close(); });
    dr.querySelector('[data-close]').addEventListener('click', close);
    document.addEventListener('keydown', e => { if (e.key === 'Escape' && dr.classList.contains('open')) close(); });
  }
  function open(html, title = '', cb = null) {
    ensure(); body.innerHTML = html; titleEl.textContent = title; body.scrollTop = 0; onClose = cb;
    if (!dr.classList.contains('open')) opener = document.activeElement;
    openedAt = performance.now();
    dr.setAttribute('aria-label', title || 'Annotation');
    dr.inert = false; behind().forEach(el => { el.inert = true; });
    back.classList.add('open'); dr.classList.add('open');
    dr.tabIndex = -1; dr.focus({ preventScroll: true });
  }
  /** opts.silent: do not run the close callback (used when Back closes the drawer). */
  function close(opts = {}) {
    if (!dr || !dr.classList.contains('open')) return;
    back.classList.remove('open'); dr.classList.remove('open');
    dr.inert = true; behind().forEach(el => { el.inert = false; });
    if (opener && opener.isConnected) opener.focus({ preventScroll: true });
    const f = onClose; onClose = null;
    if (f && !opts.silent) f();
  }
  return { open, close, get isOpen() { return !!(dr && dr.classList.contains('open')); }, get body() { ensure(); return body; } };
})();

/* ---------------------------------------------------------------- citations */
/* A citation link opens its full reference just after itself, as a small disclosure:
   focus moves into it, Tab continues from it, Escape closes it and returns to the link. */
(function () {
  let pop = null;
  function bibFor(key) { return (FC.biblio || []).find(b => b.key === key); }
  function hide() {
    if (!pop) return;
    if (pop._for) pop._for.setAttribute('aria-expanded', 'false');
    pop.remove(); pop = null;
  }
  document.addEventListener('click', e => {
    const a = e.target.closest('a.cite');
    if (!a) { if (pop && !e.target.closest('.cite-pop')) hide(); return; }
    const b = bibFor(a.dataset.key);
    if (!b) return;                              // unknown: let the link work
    e.preventDefault();
    const was = pop && pop._for === a;
    hide();
    if (was) return;                             // a second click closes it
    // only a web address or a page of this site, and escaped: the href comes from the content
    const raw = a.getAttribute('href') || '';
    const href = /^(https?:\/\/|(?:text|about|atlas)\.html(?:#|$)|#)/.test(raw) ? raw : 'about.html#bib-' + b.key;
    const go = href.startsWith('text.html') ? 'Open this page of the book →' : href.startsWith('http') ? 'Open the source →' : 'See the bibliography →';
    pop = FC.util.html(`<span class="cite-pop" role="group" aria-label="Reference" tabindex="-1">${b.html}<a class="go" href="${FC.util.esc(href)}"${href.startsWith('http') ? ' target="_blank" rel="noopener"' : ''}>${go}</a></span>`);
    pop._for = a; a.setAttribute('aria-expanded', 'true');
    a.after(pop);                                // next in the tab order
    const r = a.getBoundingClientRect(), pr = pop.getBoundingClientRect();
    pop.style.left = FC.util.clamp(r.left, 16, innerWidth - pr.width - 16) + 'px';
    pop.style.top = (r.bottom + pr.height + 8 < innerHeight ? r.bottom + 6 : Math.max(8, r.top - pr.height - 6)) + 'px';
    pop.focus({ preventScroll: true });
    pop.addEventListener('keydown', ev => {
      if (ev.key === 'Escape') { ev.stopPropagation(); ev.preventDefault(); const o = pop && pop._for; hide(); if (o) o.focus(); }
    });
    pop.addEventListener('focusout', ev => {
      if (pop && ev.relatedTarget && !pop.contains(ev.relatedTarget) && ev.relatedTarget !== a) hide();
    });
  });
  // scrolling hides it (it is fixed in place), unless the scroll came from moving focus inside it
  addEventListener('scroll', () => { if (pop && !pop.contains(document.activeElement)) hide(); }, { passive: true, capture: true });
})();

/* ---------------------------------------------------------------- theme & references */
/** Label every "hide references" button with what it will do now. */
FC.syncCiteToggles = function () {
  const on = document.body.classList.contains('hide-cites');
  document.querySelectorAll('[data-toggle-cites]').forEach(b => {
    b.textContent = on ? 'Show references in the text' : 'Hide references in the text';
    b.setAttribute('aria-pressed', String(on));
  });
};
(function () {
  const root = document.documentElement;
  const t = FC.prefs.get('theme', null);
  if (t === 'dark' || t === 'light') root.dataset.theme = t;
  const isDark = () => root.dataset.theme ? root.dataset.theme === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
  document.addEventListener('DOMContentLoaded', () => {
    const btn = document.querySelector('.theme-btn');
    if (btn) {
      btn.setAttribute('aria-label', 'Dark theme');
      btn.setAttribute('aria-pressed', String(isDark()));
      btn.addEventListener('click', () => {
        root.dataset.theme = isDark() ? 'light' : 'dark';
        FC.prefs.set('theme', root.dataset.theme);
        btn.setAttribute('aria-pressed', String(isDark()));
      });
    }
    if (FC.prefs.get('hideCites', false)) document.body.classList.add('hide-cites');
    FC.syncCiteToggles();
  });
  document.addEventListener('click', e => {
    if (!e.target.closest('[data-toggle-cites]')) return;
    const on = document.body.classList.toggle('hide-cites');
    FC.prefs.set('hideCites', on);
    FC.syncCiteToggles();
  });
})();

/* ---------------------------------------------------------------- missing data */
/* If a data file named by this page did not load (an incomplete copy, a partial capture), say so
   instead of leaving an empty page. Registered before the page scripts' own handlers, so it runs first. */
document.addEventListener('DOMContentLoaded', () => {
  const missing = Array.from(document.scripts, s => s.getAttribute('src') || '')
    .filter(s => s.startsWith('data/')).map(s => s.slice(5).replace(/\.js.*$/, '')).filter(k => !FC[k]);
  if (!missing.length) return;
  const m = document.querySelector('main');
  if (m) m.insertAdjacentHTML('afterbegin', `<p class="notice" role="alert"><b>Part of this page could not be loaded</b> (${missing.map(k => FC.util.esc('data/' + k + '.js')).join(', ')}). Reload the page; if this message stays, this copy of the edition is incomplete.</p>`);
});

/* ---------------------------------------------------------------- draft notice */
/* Shown every time any page of the site is opened, by the editor's instruction:
   the edition is an AI-produced draft and must be read as one. A native <dialog>
   opened with showModal() makes the rest of the page inert and returns focus
   afterwards; Escape or the button closes it. Anything a page wants to open on
   arrival (a deep-linked annotation) waits for it: FC.afterNotice(fn). */
(function () {
  const TEXT = `
    <h2 id="ai-notice-title">An AI-produced draft</h2>
    <p>The transcriptions, translations, annotations, essays and the reconstruction of the game’s rules on this site were produced by Claude, an AI model made by Anthropic.</p>
    <p><b>It is a draft.</b> No specialist has reviewed it. It should not be trusted, cited or taken as scholarship until that review has happened.</p>
    <p>The quotations, the transcriptions and the readings of the board were checked against their sources, but by further passes of the same AI. The readings, translations and interpretations have not been checked by a specialist, and some will be wrong.</p>
    <p class="small"><a href="about.html#credits">Who made this edition, and how</a></p>
    <form method="dialog"><button class="btn primary" value="ok" autofocus>I understand</button></form>`;
  document.addEventListener('DOMContentLoaded', () => {
    const d = document.createElement('dialog');
    d.className = 'ai-notice';
    d.setAttribute('aria-labelledby', 'ai-notice-title');
    d.innerHTML = TEXT;
    document.body.append(d);
    if (typeof d.showModal === 'function') d.showModal();
    else d.setAttribute('open', '');           // very old browsers: shown, not modal
    d.addEventListener('close', () => d.remove());
  });
})();
/** Run fn once the draft notice (if it is open) has been dismissed. */
FC.afterNotice = function (fn) {
  const d = document.querySelector('dialog.ai-notice[open]');
  if (d) d.addEventListener('close', () => setTimeout(fn, 0), { once: true }); else fn();
};
