/* =========================================================================
   common.js — shared by every page.

   Contents
     FC.util        tiny DOM helpers
     FC.prefs       remembered choices (edition, theme, citations) — optional,
                    wrapped in try/catch because storage may be unavailable
     FC.sq          what we know about each square (names, kinds, verses, images)
     FC.tokens      the players' markers, drawn as small SVGs
     FC.Viewer      the pan-and-zoom board with clickable squares and tokens
     FC.annotate    builds the full annotation of a square (used by Play and Atlas)
     FC.drawer      a side sheet for reading annotations without leaving the page
     citation pop-ups, theme button, "hide references" toggle

   Data (window.FC.board, .annotations, .text, .biblio, .story) comes from
   data/*.js, generated by tools/build_data.py from the files in content/.
   ========================================================================= */
window.FC = window.FC || {};

/* ---------------------------------------------------------------- util */
FC.util = {
  $: (sel, root = document) => root.querySelector(sel),
  $$: (sel, root = document) => Array.from(root.querySelectorAll(sel)),
  esc: s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])),
  /** Create an element from an HTML string. */
  html(str) { const t = document.createElement('template'); t.innerHTML = str.trim(); return t.content.firstElementChild; },
  clamp: (v, a, b) => Math.max(a, Math.min(b, v)),
  plural: (n, one, many) => `${n} ${Math.abs(n) === 1 ? one : many}`,
};

/* ---------------------------------------------------------------- prefs */
FC.prefs = {
  // keys are prefixed because every GitHub Pages site of one user shares one storage origin
  get(k, d) { try { const v = localStorage.getItem('filosofia-cortesana:' + k); return v === null ? d : JSON.parse(v); } catch (e) { return d; } },
  set(k, v) { try { localStorage.setItem('filosofia-cortesana:' + k, JSON.stringify(v)); } catch (e) { /* storage unavailable: fine */ } },
};

/* ---------------------------------------------------------------- editions */
FC.EDITIONS = {
  C: { id: 'C', short: 'Naples 1588', long: 'Naples, Joseph Cacchij, 1588 — with Mario Cartaro’s bilingual board (the sheet you see)' },
  M: { id: 'M', short: 'Madrid 1587 (Madrigal)', long: 'Madrid, Pedro Madrigal, 1587 — second edition, with the full “Declaración del juego” (board lost)' },
  G: { id: 'G', short: 'Madrid 1587 (princeps)', long: 'Madrid, widow of Alonso Gómez, 1587 — first edition (board lost; Poverty on 59; other Labour verses)' },
};

/* ---------------------------------------------------------------- squares */
FC.sq = (function () {
  const B = () => FC.board;
  const LABOUR = [4, 12, 17, 23, 30, 34, 41, 48, 57];
  // Which fixed verse translation (TRANSLATION_GUIDE.md id) belongs to which square.
  const VID = { 1: 's1', 4: 't0', 12: 't1', 17: 't2', 23: 't3', 30: 't4', 34: 't5', 41: 't6', 48: 't7', 57: 't8',
    7: 'h7', 10: 'h10', 15: 'h15', 20: 'h20', 26: 'h26', 28: 'h28', 32: 'h32', 36: 'h36', 39: 'h39',
    43: 'h43', 46: 'h46', 51: 'h51', 53: 'h53', 55: 'h55', 60: 'h60', 63: 'h63' };
  // The princeps (G) printed eight Labour couplets of its own, in this order (Lucero 2016,
  // collation tables). Its board is lost: we lay them on Cartaro's Labour squares in order.
  const G_LABOUR = { 12: 'g1', 17: 'g2', 23: 'g3', 30: 't5', 34: 't7', 41: 'g6', 48: 't4', 57: 't3' };

  function povertySquare(ed) { return ed === 'G' ? 59 : 60; }
  function annId(n, ed) {
    if (ed === 'G' && n === 59) return 'sq60';
    if (ed === 'G' && n === 60) return 'plain';
    return FC.annotations['sq' + n] ? 'sq' + n : 'plain';
  }
  function data(n) { return B().squares[n - 1]; }
  function adorned(n, ed) {
    if (ed === 'G' && n === 59) return true;
    return !!FC.annotations['sq' + n];
  }
  function name(n, ed) {
    const a = FC.annotations[annId(n, ed)];
    if (!a || a.id === 'plain') return `Square ${n}`;
    return a.title_en.replace(/\s*\(.*\)$/, '');
  }
  /** The verse on square n in edition ed: {en, lit, es_book, es_board, it_board, gloss_it} */
  function verse(n, ed) {
    const d = data(n), V = B().verses;
    let vid = VID[n];
    if (ed === 'G' && G_LABOUR[n]) vid = G_LABOUR[n];
    if (ed === 'G' && n === 59) vid = 'h60';
    if (ed === 'G' && n === 60) vid = null;
    const v = vid ? V[vid] : null;
    const onBoard = !(ed === 'G' && (G_LABOUR[n] || n === 59 || n === 60));
    return v ? {
      vid, en: v.en, lit: v.lit, es_book: v.es.replace(/\s*\((?:1587 )?princeps only\)/, ''),
      es_board: onBoard ? d.es : '', it_board: onBoard ? d.it : '', gloss_it: onBoard ? d.it_gloss : '',
      princeps_only: vid.startsWith('g'),
    } : null;
  }
  const tile = n => `img/sq/tile-${String(n).padStart(2, '0')}.jpg`;
  const detail = n => `img/sq/detail-${String(n).padStart(2, '0')}.jpg`;
  /** Barros's own prose about square n (Naples 1588 segments; Madrigal additions too). */
  function barros(n) {
    const tag = LABOUR.includes(n) ? ['labour', String(n)] : [String(n)];
    const C = FC.text.C.filter(s => s.kind !== 'rules' && s.squares.some(x => tag.includes(x)));
    const M = FC.text.M.filter(s => s.kind !== 'rules' && s.squares.includes(String(n)));
    return { C, M };
  }
  return { LABOUR, VID, G_LABOUR, data, name, verse, tile, detail, barros, adorned, annId, povertySquare };
})();

/* ---------------------------------------------------------------- tokens */
/* Barros's worked example uses a ring, a real de a dos and a doblón as markers,
   and asks that every player have "su señal diferente". */
FC.tokens = {
  list: [
    { id: 'ring', name: 'a ring (sortija)', color: '#b08a2e' },
    { id: 'real', name: 'a real de a dos', color: '#8f969c' },
    { id: 'doblon', name: 'a doblón', color: '#c9a13b' },
    { id: 'seal', name: 'a wax seal', color: '#9c2f22' },
    { id: 'key', name: 'a key', color: '#5b5147' },
    { id: 'rosary', name: 'a rosary bead', color: '#2f5d62' },
  ],
  /** SVG markup for a marker, centred on 0,0 in a 40×40 box. */
  glyph(id) {
    switch (id) {
      case 'ring': return '<circle r="12" fill="none" stroke="#b08a2e" stroke-width="5"/><circle cy="-13" r="5" fill="#9c2f22" stroke="#6d1f16" stroke-width="1.5"/>';
      case 'real': return '<circle r="15" fill="#c7ccd0" stroke="#6f767c" stroke-width="2"/><path d="M0-9v18M-9 0h18" stroke="#5f666b" stroke-width="2.5"/><circle r="11" fill="none" stroke="#8f969c" stroke-width="1" stroke-dasharray="2 2"/>';
      case 'doblon': return '<circle r="15" fill="#e2bd57" stroke="#8a6a1b" stroke-width="2"/><rect x="-6" y="-8" width="12" height="15" rx="2" fill="none" stroke="#8a6a1b" stroke-width="2"/><path d="M-6-2h12" stroke="#8a6a1b" stroke-width="1.5"/>';
      case 'seal': return '<path d="M0-15l4 3 5-1 1 5 4 3-2 5 2 5-4 3-1 5-5-1-4 3-4-3-5 1-1-5-4-3 2-5-2-5 4-3 1-5 5 1z" fill="#a73325" stroke="#6d1f16" stroke-width="1.5"/><circle r="6" fill="none" stroke="#e8b2a6" stroke-width="1.5"/>';
      case 'key': return '<circle cx="-7" r="7" fill="none" stroke="#4b433c" stroke-width="4"/><path d="M0 0h15M10 0v6M14 0v5" stroke="#4b433c" stroke-width="4" stroke-linecap="round"/>';
      case 'rosary': return '<circle r="13" fill="#2f5d62" stroke="#1b3a3e" stroke-width="2"/><path d="M0-8v16M-5-3h10" stroke="#d9e8e6" stroke-width="2.5"/>';
    }
    return '<circle r="12" fill="#777"/>';
  },
  svg(id, cls = 'tok-ic') { return `<svg class="${cls}" viewBox="-20 -20 40 40" aria-hidden="true">${this.glyph(id)}</svg>`; },
};

/* ---------------------------------------------------------------- viewer */
/**
 * FC.Viewer — shows the board sheet with pan & zoom (wheel, drag, pinch, buttons),
 * an SVG overlay of the 63 squares (clickable), and players' tokens.
 * Coordinates everywhere are fractions of the sheet (0..1).
 */
FC.Viewer = class {
  constructor(container, opts = {}) {
    this.el = container;
    // wheel: zoom with the mouse wheel (false in the introduction, where the wheel scrolls the page)
    this.opts = Object.assign({ src: 'img/board/board-2000.jpg', hotspots: true, tools: true, onSquare: null, tips: true, wheel: true }, opts);
    const S = FC.board.sheet;
    this.aspect = S.h / S.w;
    this.el.classList.add('viewer');
    this.el.innerHTML = `
      <div class="stage">
        <img alt="Mario Cartaro, Filosofia cortesana de Alonso de Barros, Naples 1588, etching and engraving. British Museum 1869,0410.2463.+" src="${this.opts.src}" loading="lazy">
        <svg class="overlay" viewBox="0 0 1000 ${Math.round(1000 * this.aspect)}" preserveAspectRatio="none"><g class="hots"></g><g class="names" hidden></g><g class="marks"></g><g class="toks"></g></svg>
      </div>
      ${this.opts.tools ? `<div class="viewer-tools"><button type="button" data-z="in" aria-label="Zoom in">+</button><button type="button" data-z="out" aria-label="Zoom out">−</button><button type="button" data-z="fit" aria-label="Show whole board">⤢</button></div>` : ''}
      <div class="label-tip" hidden></div>`;
    this.stage = this.el.querySelector('.stage');
    this.svg = this.el.querySelector('svg');
    this.tip = this.el.querySelector('.label-tip');
    this.s = 1; this.x = 0; this.y = 0;
    if (this.opts.hotspots) this.drawHotspots();
    this.bind();
    this.ro = new ResizeObserver(() => this.layout());
    this.ro.observe(this.el);
    this.layout();
  }
  /** fraction → overlay units */
  u(p) { return [p[0] * 1000, p[1] * 1000 * this.aspect]; }
  drawHotspots() {
    const g = this.svg.querySelector('.hots');
    g.innerHTML = FC.board.squares.map(s => {
      const pts = s.quad.map(p => this.u(p).join(',')).join(' ');
      return `<polygon class="hot" data-n="${s.n}" points="${pts}"><title>${s.n}</title></polygon>`;
    }).join('');
  }
  bind() {
    const el = this.el;
    let drag = null, pinch = null, moved = false;
    const pts = new Map();
    el.addEventListener('pointerdown', e => {
      el.setPointerCapture(e.pointerId);
      pts.set(e.pointerId, [e.clientX, e.clientY]);
      moved = false;
      if (pts.size === 1) drag = { x: e.clientX, y: e.clientY, ox: this.x, oy: this.y, t: e.target };
      if (pts.size === 2) { const [a, b] = [...pts.values()]; pinch = { d: Math.hypot(a[0] - b[0], a[1] - b[1]), s: this.s, cx: (a[0] + b[0]) / 2, cy: (a[1] + b[1]) / 2 }; drag = null; }
    });
    el.addEventListener('pointermove', e => {
      if (!pts.has(e.pointerId)) { this.hover(e); return; }
      pts.set(e.pointerId, [e.clientX, e.clientY]);
      if (pinch && pts.size === 2) {
        const [a, b] = [...pts.values()]; const d = Math.hypot(a[0] - b[0], a[1] - b[1]);
        this.zoomAt(pinch.s * d / pinch.d / this.s, pinch.cx, pinch.cy); moved = true; return;
      }
      if (drag) {
        const dx = e.clientX - drag.x, dy = e.clientY - drag.y;
        if (Math.abs(dx) + Math.abs(dy) > 4) moved = true;
        this.x = drag.ox + dx; this.y = drag.oy + dy; this.apply();
      }
    });
    const end = e => {
      pts.delete(e.pointerId);
      if (pts.size < 2) pinch = null;
      if (drag && !moved) this.click(drag.t, e);
      if (!pts.size) drag = null;
    };
    el.addEventListener('pointerup', end);
    el.addEventListener('pointercancel', e => { pts.delete(e.pointerId); drag = null; pinch = null; });
    el.addEventListener('pointerleave', () => { this.tip.hidden = true; });
    el.addEventListener('wheel', e => {
      if (!this.opts.wheel && !e.ctrlKey) return;                  // let the page scroll
      e.preventDefault(); this.zoomAt(Math.exp(-e.deltaY * 0.0016), e.clientX, e.clientY);
    }, { passive: false });
    el.querySelectorAll('[data-z]').forEach(b => b.addEventListener('pointerdown', e => e.stopPropagation()));
    el.querySelectorAll('[data-z]').forEach(b => b.addEventListener('click', e => {
      e.stopPropagation();
      const r = el.getBoundingClientRect();
      if (b.dataset.z === 'fit') this.fit(true);
      else this.zoomAt(b.dataset.z === 'in' ? 1.5 : 1 / 1.5, r.left + r.width / 2, r.top + r.height / 2, true);
    }));
    el.addEventListener('keydown', e => {
      const r = el.getBoundingClientRect();
      if (e.key === '+' || e.key === '=') this.zoomAt(1.3, r.left + r.width / 2, r.top + r.height / 2, true);
      if (e.key === '-') this.zoomAt(1 / 1.3, r.left + r.width / 2, r.top + r.height / 2, true);
      if (e.key === '0') this.fit(true);
    });
    el.tabIndex = 0;
  }
  hover(e) {
    if (!this.opts.tips) return;
    const t = e.target.closest && e.target.closest('.hot');
    if (!t) { this.tip.hidden = true; return; }
    const n = +t.dataset.n, ed = this.edition || 'C';
    const r = this.el.getBoundingClientRect();
    this.tip.textContent = `${n} · ${FC.sq.name(n, ed)}`;
    this.tip.hidden = false;
    this.tip.style.left = Math.min(e.clientX - r.left + 14, r.width - 180) + 'px';
    this.tip.style.top = (e.clientY - r.top + 14) + 'px';
  }
  click(target) {
    const t = target.closest && target.closest('.hot');
    if (t && this.opts.onSquare) this.opts.onSquare(+t.dataset.n);
  }
  layout() {
    const r = this.el.getBoundingClientRect();
    this.W = r.width; this.H = r.height;
    const baseW = Math.min(r.width, r.height / this.aspect);
    this.base = baseW;
    this.stage.style.width = baseW + 'px';
    this.stage.style.height = baseW * this.aspect + 'px';
    if (!this._fitted) { this.fit(false); this._fitted = true; } else this.apply();
  }
  fit(anim) {
    this.s = 1;
    this.x = (this.W - this.base) / 2; this.y = (this.H - this.base * this.aspect) / 2;
    this.apply(anim);
  }
  zoomAt(f, cx, cy, anim) {
    const r = this.el.getBoundingClientRect();
    const ns = FC.util.clamp(this.s * f, 0.6, 9);
    f = ns / this.s;
    const px = cx - r.left, py = cy - r.top;
    this.x = px - (px - this.x) * f; this.y = py - (py - this.y) * f; this.s = ns;
    this.apply(anim);
  }
  /** Zoom so that the rectangle (fractions of the sheet) fills the view. */
  focusRect(x0, y0, x1, y1, anim = true, pad = 0.08) {
    const w = (x1 - x0) * this.base, h = (y1 - y0) * this.base * this.aspect;
    const s = FC.util.clamp(Math.min(this.W / (w * (1 + pad * 2)), this.H / (h * (1 + pad * 2))), 0.6, 9);
    this.s = s;
    this.x = this.W / 2 - ((x0 + x1) / 2) * this.base * s;
    this.y = this.H / 2 - ((y0 + y1) / 2) * this.base * this.aspect * s;
    this.apply(anim);
  }
  focusSquare(n, anim = true, zoom = 3.2) {
    const q = FC.board.squares[n - 1].quad;
    const xs = q.map(p => p[0]), ys = q.map(p => p[1]);
    const cx = (Math.min(...xs) + Math.max(...xs)) / 2, cy = (Math.min(...ys) + Math.max(...ys)) / 2;
    const half = 0.5 / zoom;
    this.focusRect(cx - half, cy - half * 0.8, cx + half, cy + half * 0.8, anim, 0);
  }
  apply(anim) {
    // keep the sheet in view: centre it when smaller than the viewer, otherwise stop at its edges
    const w = this.base * this.s, h = this.base * this.aspect * this.s;
    this.x = w <= this.W ? (this.W - w) / 2 : FC.util.clamp(this.x, this.W - w, 0);
    this.y = h <= this.H ? (this.H - h) / 2 : FC.util.clamp(this.y, this.H - h, 0);
    if (!this.hi && this.opts.src.includes('board-') && this.base * this.s * (window.devicePixelRatio || 1) > 2200) {  // sharper image once zoomed in
      this.hi = true;
      const img = this.stage.querySelector('img'), hi = new Image();
      hi.onload = () => { img.src = hi.src; };
      hi.src = 'img/board/board-full.jpg';
    }
    this.stage.style.transition = anim ? 'transform .7s cubic-bezier(.3,.1,.2,1)' : 'none';
    this.stage.style.transform = `translate(${this.x}px, ${this.y}px) scale(${this.s})`;
  }
  /** Mark squares with a CSS class (e.g. 'focus', 'dest', 'variant'). */
  mark(ns, cls) {
    this.svg.querySelectorAll('.hot.' + cls).forEach(p => p.classList.remove(cls));
    [].concat(ns || []).forEach(n => { const p = this.svg.querySelector(`.hot[data-n="${n}"]`); if (p) p.classList.add(cls); });
  }
  /** English names written over the adorned squares (a reading aid; off by default). */
  names(on, ed = 'C') {
    const g = this.svg.querySelector('.names');
    g.hidden = !on;
    if (!on) return;
    let h = '';
    for (let n = 1; n <= 63; n++) {
      if (!FC.sq.adorned(n, ed)) continue;
      const nm = FC.sq.name(n, ed).replace(/^The /, ''), c = this.u(FC.board.squares[n - 1].center);
      const w = nm.length * 6.4 + 10;
      h += `<g transform="translate(${c[0].toFixed(1)},${(c[1] + 18).toFixed(1)})"><rect x="${-w / 2}" y="-9" width="${w}" height="16" rx="3" class="name-bg"/><text class="name-tx" text-anchor="middle" y="3">${FC.util.esc(nm)}</text></g>`;
    }
    g.innerHTML = h;
  }
  /** Small labels written on the overlay (used for the princeps' Poverty on 59). */
  labels(list) {
    const g = this.svg.querySelector('.marks');
    g.innerHTML = (list || []).map(l => {
      const c = this.u(FC.board.squares[l.n - 1].center);
      return `<text class="variant-label" x="${c[0]}" y="${c[1] + 26}" text-anchor="middle">${FC.util.esc(l.text)}</text>`;
    }).join('');
  }
  /**
   * Draw tokens. players: [{id, token, color, pos}] ; pos 0 = before the gate.
   * Several tokens on the same place are fanned out.
   */
  tokens(players) {
    const g = this.svg.querySelector('.toks');
    const byPos = {};
    players.forEach(p => { (byPos[p.pos] = byPos[p.pos] || []).push(p); });
    const gate = this.u([0.13, 0.85]);
    let out = '';
    Object.entries(byPos).forEach(([pos, ps]) => {
      pos = +pos;
      const c = pos === 0 ? gate : this.u(FC.board.squares[pos - 1].center);
      ps.forEach((p, i) => {
        const k = ps.length, ang = (i / k) * Math.PI * 2, rad = k > 1 ? 20 : 0;
        const x = c[0] + Math.cos(ang) * rad, y = c[1] + Math.sin(ang) * rad;
        out += `<g class="token" data-player="${p.id}" transform="translate(${x.toFixed(1)},${y.toFixed(1)})">
          <circle r="21" fill="rgba(250,245,234,.92)" stroke="${p.color}" stroke-width="4"/>
          <g transform="scale(0.85)">${FC.tokens.glyph(p.token)}</g></g>`;
      });
    });
    g.innerHTML = out;
  }
};

/* ---------------------------------------------------------------- annotate */
/**
 * FC.annotate(n, edition) → HTML for square n (1..63), or for a feature id
 * ('gate', 'centre-sea', 'corner-clock', 'title', …).
 */
FC.annotate = function (key, ed = 'C', opts = {}) {
  const { esc } = FC.util;
  const isSq = typeof key === 'number';
  const aid = isSq ? FC.sq.annId(key, ed) : key;
  const a = FC.annotations[aid] || FC.annotations.plain;
  const n = isSq ? key : null;
  const title = isSq ? FC.sq.name(n, ed) : a.title_en;
  const d = isSq ? FC.sq.data(n) : null;
  let h = '';
  h += `<div class="sq-head">${n ? `<div class="sq-num">${n}</div>` : ''}<div><h2 class="sq-title">${esc(title)}</h2>`;
  const subs = [];
  if (a.title_es && a.id !== 'plain') subs.push(`<span lang="es">${esc(a.title_es)}</span>`);
  if (a.board_it && !/^\(none/.test(a.board_it) && a.id !== 'plain') subs.push(`<span lang="it">${esc(a.board_it)}</span>`);
  h += `<div class="sq-sub">${subs.join(' · ')}</div></div></div>`;

  // image
  const img = n ? FC.sq.detail(n) : FC.featureImage(aid);
  if (img) h += `<figure class="sq-figure"><img loading="lazy" src="${img}" alt="${esc(title)}: detail of the board"><figcaption>Detail of Cartaro’s board (Naples 1588). © The Trustees of the British Museum.${n ? ` <a href="#" data-show-on-board="${n}">Show on the whole board</a>` : ''}</figcaption></figure>`;

  // edition note for the princeps' Poverty
  if (ed === 'G' && n === 59) h += `<p class="notice">In the first edition (Madrid, widow of Alonso Gómez, 1587) Poverty stands on square <b>59</b>, not 60; the board printed with that edition is lost. We show Cartaro’s picture of square 60 here.</p>`;
  if (ed === 'G' && n === 60) h += `<p class="notice">In the first edition Poverty stands on 59, so under that edition’s rules this square is plain. On the surviving board (and in the later editions) it is Poverty.</p>`;

  // verse
  const v = n ? FC.sq.verse(n, ed) : null;
  if (v) {
    h += `<div class="verse"><div class="en">${esc(v.en).replace(' / ', '<br>')}</div><div class="lit">Literally: ${esc(v.lit)}</div><div class="orig">`;
    if (v.es_board) h += `<div><b>Spanish, on the board</b><span lang="es">${esc(v.es_board).replace(' / ', '<br>')}</span></div>`;
    if (v.it_board) h += `<div><b>Italian, on the board</b><span lang="it">${esc(v.it_board).replace(' / ', '<br>')}</span>${v.gloss_it ? `<div class="small muted">(${esc(v.gloss_it)})</div>` : ''}</div>`;
    const bookLab = ed === 'G' ? 'Madrid 1587, first edition' : ed === 'M' ? 'Madrid 1587 and Naples 1588 books' : 'Naples 1588 book';
    if (!v.es_board && ed === 'G' && FC.sq.G_LABOUR[n]) h += `<div class="small muted">Cartaro’s board, made for the later text, has a different couplet here: <i lang="es">${esc(FC.sq.data(n).es)}</i>.</div>`;
    h += `<div><b>Spanish, ${bookLab}${v.princeps_only ? ' (this couplet only in the first edition)' : ''}</b><span lang="es">${esc(v.es_book).replace(' / ', '<br>')}</span></div>`;
    h += `</div></div>`;
  }
  // rule
  if (a.rule_short || (d && d.rule)) {
    h += `<div class="rulebox"><div class="ic">☞</div><div>${a.rule_short || ''}`;
    if (d && d.rule) h += `<div class="lab">On the board: <i lang="it">${esc(d.rule)}</i>${d.rule_en ? ` — ${esc(d.rule_en)}` : ''}</div>`;
    h += `</div></div>`;
  }
  const sect = (t, body, open) => body ? `<details class="sect"${open ? ' open' : ''}><summary>${t}</summary>${body}</details>` : '';
  h += sect('What you see', a.see, true);
  h += sect('Why it is here', a.why, true);
  if (n) {
    const b = FC.sq.barros(n);
    if (b.C.length) {
      let bh = `<p class="small muted">Barros’s own explanation, from the Naples 1588 book (Spanish as printed; English translation by this edition). <a href="text.html#${b.C[0].id}">Read it in the whole book →</a></p>`;
      b.C.forEach(s => {
        bh += `<div class="barros-seg"><div class="meta">${s.page ? 'p. ' + esc(s.page) : 'sig. ' + esc(s.sig)} · Naples 1588</div><div class="es" lang="es">${esc(s.es).replace(/ \/ /g, '<br>')}</div><div class="en">${s.kind === 'verse' ? esc(s.en).replace(' / ', '<br>') : s.en}</div></div>`;
      });
      if (b.M.length && ed === 'M') {   // Madrigal's additions are not in G or C
        bh += `<p class="small muted">Additions and differences in the Madrid (Madrigal) edition of 1587, from a modernized transcription:</p>`;
        b.M.forEach(s => { bh += `<div class="barros-seg"><div class="meta">fol. ${esc(s.fol)} · Madrid 1587 (Madrigal)</div><div class="es" lang="es">${esc(s.es)}</div><div class="en">${s.en}</div></div>`; });
      }
      h += sect('What Barros says', bh, false);
    }
  }
  h += sect('Historical context', a.context, false);
  h += sect('Differences between the editions', a.variants, false);
  h += sect('What scholars say', a.readings, false);
  if (n && FC.sq.LABOUR.includes(n) && FC.annotations.labour) {
    const L = FC.annotations.labour;
    h += sect('About all nine Labour squares', L.why + L.context + L.variants + L.readings, false);
  }
  if (n && d && d.desc && aid === 'plain') h += `<p class="small muted">On the board: ${esc(d.desc)}</p>`;
  return h;
};
FC.featureImage = function (aid) {
  const map = { gate: 'entrance_gate', 'corner-swan': 'corner_bl_swan', 'corner-dolphin': 'corner_tl_figure', 'corner-occasion': 'corner_tr_figure',
    'corner-clock': 'corner_br_clock', 'centre-man': 'palm_man', 'centre-sea': 'field', title: 'signature', labour: null };
  return map[aid] ? `img/feat/${map[aid]}.jpg` : (aid === 'labour' ? FC.sq.detail(4) : null);
};

/* ---------------------------------------------------------------- drawer */
FC.drawer = (function () {
  let back, dr, body, titleEl, onClose = null, openedAt = 0, opener = null;
  const behind = () => Array.from(document.body.children).filter(el => el !== dr && el !== back);
  function ensure() {
    if (dr) return;
    back = FC.util.html('<div class="drawer-backdrop"></div>');
    dr = FC.util.html(`<aside class="drawer" role="dialog" aria-modal="true" aria-label="Annotation">
      <div class="drawer-head"><span class="grow sc drawer-title"></span><button class="btn small" data-close>Close ✕</button></div>
      <div class="drawer-body"></div></aside>`);
    document.body.append(back, dr);
    body = dr.querySelector('.drawer-body'); titleEl = dr.querySelector('.drawer-title');
    dr.inert = true;
    // a touch that opened the drawer also sends a click to the backdrop beneath it: ignore that one
    back.addEventListener('click', () => { if (performance.now() - openedAt > 400) close(); });
    dr.querySelector('[data-close]').addEventListener('click', close);
    document.addEventListener('keydown', e => { if (e.key === 'Escape' && dr.classList.contains('open')) close(); });
  }
  function open(html, title = '', cb = null) {
    ensure(); body.innerHTML = html; titleEl.textContent = title; body.scrollTop = 0; onClose = cb;
    opener = document.activeElement; openedAt = performance.now();
    dr.setAttribute('aria-label', title || 'Annotation');
    dr.inert = false; behind().forEach(el => { el.inert = true; });
    back.classList.add('open'); dr.classList.add('open');
    dr.tabIndex = -1; dr.focus({ preventScroll: true });
  }
  function close() {
    if (!dr || !dr.classList.contains('open')) return;
    back.classList.remove('open'); dr.classList.remove('open');
    dr.inert = true; behind().forEach(el => { el.inert = false; });
    if (opener && opener.isConnected) opener.focus({ preventScroll: true });
    if (onClose) { const f = onClose; onClose = null; f(); }
  }
  return { open, close, get body() { ensure(); return body; } };
})();

/* ---------------------------------------------------------------- citations */
(function () {
  let pop = null;
  function bibFor(key) { return (FC.biblio || []).find(b => b.key === key); }
  function hide() { if (pop) { pop.remove(); pop = null; } }
  document.addEventListener('click', e => {
    const a = e.target.closest('a.cite');
    if (!a) { if (pop && !e.target.closest('.cite-pop')) hide(); return; }
    const b = bibFor(a.dataset.key);
    if (!b) return;                              // unknown: let the link work
    e.preventDefault(); hide();
    const href = a.getAttribute('href');
    pop = FC.util.html(`<div class="cite-pop" role="note">${b.html}<a class="go" href="${href}"${href.startsWith('http') ? ' target="_blank" rel="noopener"' : ''}>${href.startsWith('text.html') ? 'Open this page of the book →' : href.startsWith('http') ? 'Open the source →' : 'See the bibliography →'}</a></div>`);
    document.body.append(pop);
    const r = a.getBoundingClientRect(), pr = pop.getBoundingClientRect();
    pop.style.left = FC.util.clamp(r.left, 16, innerWidth - pr.width - 16) + 'px';
    pop.style.top = (r.bottom + pr.height + 8 < innerHeight ? r.bottom + 6 : Math.max(8, r.top - pr.height - 6)) + 'px';
  });
  addEventListener('scroll', hide, { passive: true, capture: true });
})();

/* ---------------------------------------------------------------- theme & references */
(function () {
  const root = document.documentElement;
  const t = FC.prefs.get('theme', null);
  if (t) root.dataset.theme = t;
  document.addEventListener('DOMContentLoaded', () => {
    const btn = document.querySelector('.theme-btn');
    if (btn) btn.addEventListener('click', () => {
      const dark = root.dataset.theme ? root.dataset.theme === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches;
      root.dataset.theme = dark ? 'light' : 'dark';
      FC.prefs.set('theme', root.dataset.theme);
    });
    if (FC.prefs.get('hideCites', false)) document.body.classList.add('hide-cites');
    const cb = document.querySelector('[data-toggle-cites]');
    if (cb) {
      cb.textContent = document.body.classList.contains('hide-cites') ? 'Show references in the text' : 'Hide references in the text';
      cb.addEventListener('click', () => {
        const on = document.body.classList.toggle('hide-cites');
        FC.prefs.set('hideCites', on);
        cb.textContent = on ? 'Show references in the text' : 'Hide references in the text';
      });
    }
  });
})();

/* ---------------------------------------------------------------- draft notice */
/* Shown every time any page of the site is opened, by the editor's instruction:
   the edition is an AI-produced draft and must be read as one. A native <dialog>
   opened with showModal() makes the rest of the page inert and returns focus
   afterwards; Escape or the button closes it. */
(function () {
  const TEXT = `
    <h2 id="ai-notice-title">An AI-produced draft</h2>
    <p>Everything on this site — the transcriptions, translations, annotations, essays and the reconstruction of the game’s rules — was produced by Claude, an AI model made by Anthropic.</p>
    <p><b>It is a draft.</b> No specialist has reviewed it. It should not be trusted, cited or taken as scholarship until that review has happened.</p>
    <p>The quotations were checked by program against their sources. The readings, translations and interpretations were not, and some will be wrong.</p>
    <p class="small"><a href="about.html#credits">Who made this edition, and how</a></p>
    <form method="dialog"><button class="btn primary" value="ok" autofocus>I understand</button></form>`;
  document.addEventListener('DOMContentLoaded', () => {
    const d = document.createElement('dialog');
    d.className = 'ai-notice';
    d.setAttribute('aria-labelledby', 'ai-notice-title');
    d.innerHTML = TEXT;
    document.body.append(d);
    if (typeof d.showModal === 'function') d.showModal();
    else d.setAttribute('open', '');           // very old browsers: shown, not modal
    d.addEventListener('close', () => d.remove());
  });
})();
